// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ModifyWin;

{ITE} {DFMFileType} {main.dfm}
{ITE} {RCFileType} {ModifyWin_DRC.rc}

{$R 'main.dfm' Form1:TForm}
{$R 'ModifyWin_DRC.res' 'ModifyWin_DRC.rc'}

{$E chs}

begin
end.